### ISSUE TITLE
New download restriction rows do not save in metabox

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/EDD-Content-Restriction#77]
When creating a WordPress Page and configuring which downloads will restrict that page, you can add a new download (repeatable row) but it will not save when you Save/Update the page. 

This is only broken on EDD `release/2.8` branch. It works fine on EDD `master`. 

I cannot figure out if this is because of [EDD issue 2704](https://github.com/easydigitaldownloads/easy-digital-downloads/issues/2704) or not, but in fixing its recent issue with not being able to remove repeatable rows, I found this issue.

@cklosowski any help with tracking this down would be appreciated. Having a hard time telling if 2704 is a red herring or not.

**Comment by pippinsplugins** [comment]
I've confirmed it only happens on release/2.8 but don't yet see why.

I don't think https://github.com/easydigitaldownloads/easy-digital-downloads/issues/2704 is related. If it was it would almost certainly be due to HTML changes of the repeatable rows, but I've compared the resulting HTML between master and release/2.8 of core and they're identical for Content Restriction.

**Comment by mintplugins** [comment]
Confirmed. Now that 2.8 is released I think this is more of a priority. Customer ticket reporting it here:
https://secure.helpscout.net/conversation/414142903/64826/?folderId=180499

**Comment by mintplugins** [comment]
I did some digging and found it's caused by the JS setting the values of all fields to empty - which happens to include nonce fields. Because those nonce fields are submitted as blank, it doesn't pass the nonce check in CR. 

The values of all fields are set to empty here:
https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/assets/js/admin-scripts.js#L42

**Comment by mintplugins** [comment]
By moving the nonce field outside the repeatable rows, this is solved.

**Comment by SDavisMedia** [comment]
It's fixing the repeatable rows but causing the checkbox settings to duplicate.

<img width="646" alt="screenshot 2017-08-14 18 33 38" src="https://user-images.githubusercontent.com/2359131/29298779-29e875d0-811f-11e7-86c5-a026e54f0faa.png">

**Comment by mintplugins** [comment]
I've confirmed that the duplicate checkboxes are an issue on CR master and in EDD 2.7 - which indicated this is a separate bug altogether. I've opened a separate issue for that here:

https://github.com/easydigitaldownloads/EDD-Content-Restriction/issues/79

**Comment by pippinsplugins** [comment]
Another report of this.

**Comment by pippinsplugins** [comment]
PR works for me.

**Comment by pippinsplugins** [comment]
Deploying now.
